# Generated by Django 4.1.2 on 2022-10-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('writer', models.CharField(default='', max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('recommend', models.IntegerField(default=0)),
                ('password', models.CharField(default='', max_length=40)),
                ('contents', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
